config/routes.rb
Rails.application.routes.draw do

   root 'pages#home'
   resources :senders
   get '/login', to:"logins#new"
   post '/login', to:"logins#create"
   get '/logout', to:"logins#destroy"

end

app/models/sender.rb
class Sender < ActiveRecord::Base
  before_save { self.mail = mail.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :mail, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def current_user
    @current_sender ||= Sender.find(session[:sender_id]) if session[:sender_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new

  end

  def create
    sender = Sender.find_by(mail: params[:mail])
    if sender && sender.authenticate(params[:password])
      session[:sender_id] = sender.id
      flash[:success] = "you are logged in"
      redirect_to root_path
    else
      flash.now[:danger] = "Your password don't match"
      render 'new'
    end
  end

  def destroy
    session[:sender_id] = nil
    flash[:success] = "you have logged out"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  def new
    @sender = Sender.new
  end

  def create
    @sender = Sender.new(sender_params)
    if @sender.save
      flash[:success] = "Your account has been created succesfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @sender = current_user
  end

  private
    def sender_params
      params.require(:sender).permit(:name, :last_name, :mail, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyectoWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Log In</title>
  </head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <%= form_tag '/login' do %>
          <h2>Log In</h2>
          <hr class="colorgraph">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <%= label_tag :mail %>
                <%= text_field_tag :mail%>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <%= label_tag :password %>
                <%= password_field_tag :password%>
              </div>
            </div>
          </div>
          <hr class="colorgraph">
            <div class="row">
              <%= submit_tag 'Login', class: "btn btn-success" %>
            </div>
        <% end %>
        <%= link_to "<< Atrás", root_path %>
      </div>
    </div>
  </div>
</body>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="pages/custom.css">
    <title>MoneyTran$</title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MON€YTRAN$</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Home <span class="sr-only">(current)</span></a></li>
            <% if logged_in? %>
            <li><%= link_to 'Profile',sender_path(current_user) %></li>
            <% end %>
          </ul>
          <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/logout">Log Out</a></li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/login">Log In</a></li>
          </ul>
          <%end%>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <div class="jumbotron">
        <h1>Bienvenido!</h1>
        <p>MON€YTRAN$ es el sistema más sencillo para mandar dinero a tus conocidos que se encuentran fuera de tu país.</p>
        <p><%= link_to "Registrate", new_sender_path, class:'btn btn-primary btn-lg' %></p>
      </div>
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%= image_tag("pages/ex.png", :alt => "rss feed",width: '150') %>
            <div class="caption">
              <h3>No importa el tipo de moneda</h3>
              <p>Tú puedes ingresar tu dinero en dólares y las demás personas lo van a recibir en la moneda del país en el que se encuentren sin nungún cargo extra.</p>
              <p><a href="usuarios/login.php" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%= image_tag("pages/bank.png", :alt => "rss feed",width: '150') %>
            <div class="caption">
              <h3>Sin bancos</h3>
              <p>No necesitas estár afiliado a ningún banco para poder hacer las transferencias y no se te cobrará ninguna comisión extra por depósito ni por retiro</p>
              <p><a href="usuarios/login.php" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%= image_tag("pages/security.png", :alt => "rss feed",width: '150') %>
            <div class="caption">
              <h3>Seguridad</h3>
              <p>Tu dinero se encuentra asegurado ya que nuestros grandes desarrolladores han habilitado muchos sistemas de seguridad para que tú estés tranquilo</p>
              <p><a href="usuarios/login.php" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

app/views/senders/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sign Up</title>
  </head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <%= form_for @sender do |f| %>
          <h2>Regístrate <small>Es grátis</small></h2>
          <hr class="colorgraph">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Nombre' %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
              <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control input-lg', placeholder: 'Apellido'  %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <%= f.label :mail %>
                <%= f.text_field :mail, class: 'form-control input-lg', placeholder: 'E-Mail'  %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control input-lg', placeholder: 'Contraseña'  %>
              </div>
            </div>
          </div>
          <hr class="colorgraph">
            <div class="row">
              <%= f.submit(@sender.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
            </div>
        <% end %>
        <%= link_to "<< Atrás", root_path %>
      </div>
    </div>
  </div>
</body>

app/views/senders/show.html.erb
<h1>Bienvenido</h1>
<h2><%= @sender.name%> <%= @sender.last_name%></h2>